version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
    ports:
      - "3306:3306"
    networks:
      - mysql_net
    volumes:
      - mysql_data:/var/lib/mysql

  node:
    image: node:18
    container_name: node
    working_dir: /app
    networks:
      - mysql_net
    volumes:
      - .:/app
    command: sh -c "npm install && npx prisma migrate reset --force && npx prisma migrate dev --name init && npm run seed"
    depends_on:
      - mysql

volumes:
  mysql_data:

networks:
  mysql_net:
    driver: bridge

